### PR TITLE
Add the ability to use RequireAuthorization when using MapPost to add authentication policies to the graphql endpoint

### PR DESCRIPTION
**Pull request by RubberChickenParadise**
#304 Add the ability to pass authorization policies that should be applied to the Post Endpoint.  By passing in the authorization policies and using RequireAuthorization, the entire graphql endpoint can be easily secured with an authorization policy.

I added an additional optional string array parameter to the `MapGraphQL` extension and passed it to the `RequireAuthorization()` method for the `MapPost` call.

This allows using .net asp.net core authorization policies on the endpoint to enable ensuring users are authenticated

### CODE REVIEW

**Comment by lukemurray** [comment]
Thanks for this! Any chance you could update the docs with an example of how to use please?

**Comment by RubberChickenParadise** [comment]
I will work on getting the documentation updated if the coding changes will be accepted with the updated documentation.

Thanks
Jessica
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lukemurray** [comment]
Yes, the code changes look good. Thank you!

**Comment by RubberChickenParadise** [comment]
@lukemurray Documentation updated.  I put it in the Quick Start guide since security on the endpoint should be a universal requirement for most applications that want to restrict access.

**Pull request merged**
